# Generated by Django 3.1.5 on 2021-01-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
